### ISSUE TITLE
Declaration not compatible

### ISSUE THREAD

**Issue by migo315** [bestit/commercetools-odm#27]
Error found while execute via php 7.2:

> Declaration of BestIt\CommercetoolsODM\Repository\ProjectRepository::findBy(array $criteria, ?array $orderBy = NULL, $limit = NULL, $offset = NULL) must be compatible with BestIt\CommercetoolsODM\Model\DefaultRepository::findBy(array $criteria, ?array $orderBy = NULL, $limit = NULL, $offset = NULL): array in /opt/atlassian/pipelines/agent/build/vendor/bestit/commercetools-odm/src/Repository/ProjectRepository.php on line 23

Even if the method `findBy` is not used, the error will be thrown with php7.2

**Comment by migo315** [comment]
Ah, there is already an open PR: #25

**Comment by bestit-el-bardan** [comment]
This has already been fixed.
